### ISSUE TITLE
apple_set_os kernel parameter fails

### ISSUE THREAD

**Issue by vanya-robertson** [t2linux/kernel#13]
I have followed the instructions for Enabling the iGPU.
Setting `apple_set_os` in `GRUB_CMDLINE_LINUX_DEFAULT` causes `glxinfo | grep "OpenGL renderer"` to return the Intel card only when running the backup initramfs. When running the default initramfs, my console just fails to boot.
Please advise how to solve.

**Comment by Redecorating** [comment]
what mac model is this?

Maybe try regenerating the initramfs when you boot the fallback initramfs, so the default initramfs will have any modules needed for the igpu as well

**Comment by vanya-robertson** [comment]
I was running `mkinitcpio -P` after `grub-mkconfig -o /boot/grub/grub.cfg`

**Comment by vanya-robertson** [comment]
It is a 16,1 Macbook Pro.

**Comment by vanya-robertson** [comment]
I was regenerating initramfs before booting into backup. When done from the backup initramfs, it worked. Why would this be?
